name: Build chainxorg/srtool

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push the Docker image
        run: |
          git clone https://gitlab.com/chevdor/srtool --depth=1
          cd srtool
          export RUSTC_VERSION=nightly-2021-03-01
          docker build --build-arg RUSTC_VERSION=$RUSTC_VERSION -t chainxorg/srtool:$RUSTC_VERSION .
          ### docker push chainxorg/srtool:$RUSTC_VERSION
