name: Build chainxorg/srtool image

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.2
        name: Checkout code

      - name: Docker login
         env:
           DOCKER_USER: ${{secrets.DOCKER_USER}}
           DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
         run: |
           docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build the Docker image
         run: |
           git clone https://gitlab.com/chevdor/srtool --depth=1
           cd srtool
           RUSTC_VERSION=nightly-2021-03-01 && docker build --build-arg RUSTC_VERSION=$RUSTC_VERSION -t chainxorg/srtool:$RUSTC_VERSION .

      # - uses: mr-smithers-excellent/docker-build-push@v4
        # name: Build & push docker image.
        # with:
          # image: chainxorg/srtool
          # tag: ${GITHUB_REF##*/}
          # registry: docker.io
          # dockerfile: Dockerfile
          # username: ${{ secrets.DOCKER_USERNAME }}
          # password: ${{ secrets.DOCKER_PASSWORD }}

       # - name: Docker Push
          # run: docker push chamodshehanka/node-test
