name: Build chainxorg/srtool image

on:
  [push]
  # push:
    # branches:
      # - release

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        toolchain: [nightly-2021-03-01]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: |
          git clone https://gitlab.com/chevdor/srtool --depth=1
          cd srtool
          docker build --build-arg RUSTC_VERSION=${{ matrix.toolchain }} -t chainxorg/srtool:${{ matrix.toolchain }} .

      - name: Push the image to Docker Hub
        run: docker push chainxorg/srtool:${{ matrix.toolchain }}
